### PR TITLE
fix #116: improve Plugin filtering UX

### LINKED ISSUE #116: improve UX of filtering plugins

### PR DESCRIPTION
**Pull request by safareli**

### CODE REVIEW

**Comment by lambtron** [comment]
Hmm.. I'm having a hard time understanding what improvements were made here. Can you kindly elaborate? :) Thanks!

**Comment by Ajedi32** [comment]
Looks to me like this lets you click anywhere on the "plugin filter" row to focus the input field. Right now you have to specifically click on the (pretty small) input box in the middle of that row.

**Comment by lambtron** [comment]
Got it, didn't catch that. :) Thanks!

**Comment by safareli** [comment]
Welcome :3

**Pull request merged**
